### PR TITLE
Migrate CI to GitHub Actions - closes #6

### LINKED ISSUE #6: Migrate to GitHub Actions

### PR DESCRIPTION
**Pull request by DanielRuf**
This PR migrates the CI setup to GitHub Actions.

Regarding notifications, see https://help.github.com/en/articles/choosing-the-delivery-method-for-your-notifications#choosing-the-delivery-method-for-notifications-about-github-actions

### CODE REVIEW

**Comment by steambap** [comment]
Thanks!

**Comment by DanielRuf** [comment]
Ah you shouldn't have that merged already. You are not yet part of the GHA beta as it seems =)

**Comment by DanielRuf** [comment]
You can reveert it for now and I will resend it when you have GHA too.

**Comment by steambap** [comment]
I applied for GitHub Action beta, let's just wait for GitHub's response for now.

**Pull request merged**
